/* mvp.c — minimal mquickjs C function registration test
 *
 * Tests only: can a custom C function registered via CONFIG_KWCC
 * be called from JavaScript?
 *
 * No Sokol, no microui, no nanovg — pure mquickjs.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mquickjs/mquickjs.h"
#include "mquickjs_stubs.h"

/* generated by host tool with CONFIG_KWCC */
#include "mquickjs/mqjs_stdlib.h"

/* ── file loader ─────────────────────────────────────────────── */

static char *load_file(const char *path, int *pout_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    if (pout_len) *pout_len = (int)len;
    return buf;
}

/* ── js_kwcc_ui callback: prints what it receives ────────────── */

static JSValue mvp_ui_callback(JSContext *ctx, const char *method,
                               int argc, JSValue *argv) {
    printf("[C callback] method=%s, argc=%d\n", method, argc);
    for (int i = 0; i < argc; i++) {
        JSCStringBuf buf;
        const char *s = JS_ToCString(ctx, argv[i], &buf);
        printf("  arg[%d] = %s\n", i, s ? s : "(non-string)");
    }
    return JS_NewInt32(ctx, 42);
}

/* ── main ────────────────────────────────────────────────────── */

static const size_t MEM_SIZE = 1 * 1024 * 1024; /* 1MB */

int main(int argc, const char **argv) {
    if (argc < 2) {
        printf("usage: mvp test.js\n");
        return 1;
    }

    const char *js_path = argv[1];

    /* create context with our custom stdlib */
    void *mem = malloc(MEM_SIZE);
    JSContext *ctx = JS_NewContext(mem, MEM_SIZE, &js_stdlib);
    if (!ctx) {
        fprintf(stderr, "JS_NewContext failed\n");
        return 1;
    }

    /* register the UI callback — this is what makes js_kwcc_ui actually work */
    kwcc_set_ui_callback(mvp_ui_callback);

    printf("[C] context created, stdlib = %p\n", (void *)&js_stdlib);

    /* load and run JS file */
    int js_len = 0;
    char *js_code = load_file(js_path, &js_len);
    if (!js_code) return 1;

    printf("[C] loaded %s (%d bytes), executing...\n", js_path, js_len);

    JSValue result = JS_Eval(ctx, js_code, strlen(js_code), js_path, 0);
    if (JS_IsException(result)) {
        JSValue exc = JS_GetException(ctx);
        JSCStringBuf buf;
        const char *s = JS_ToCString(ctx, exc, &buf);
        fprintf(stderr, "[JS ERROR] %s\n", s ? s : "(null)");
        free(js_code);
        JS_FreeContext(ctx);
        free(mem);
        return 1;
    }

    /* print result */
    {
        JSCStringBuf buf;
        const char *s = JS_ToCString(ctx, result, &buf);
        printf("[C] JS result: %s\n", s ? s : "(undefined)");
    }

    JS_FreeContext(ctx);
    free(js_code);
    free(mem);

    printf("[C] mvp test passed\n");
    return 0;
}
